language: node_js
node_js:
  - 0.10
git:
  depth: 1
branches:
  only:
    - master
before_script:
  - "wget http://www.sqlite.org/2013/sqlite-autoconf-3080002.tar.gz"
  - "tar xvfz sqlite-autoconf-3070603.tar.gz"
  - "cd sqlite-autoconf-3070603"
  - "./configure"
  - "make"
  - "make install"
  - "which sqlite3"
  - "sqlite3 --version"
