language: node_js
node_js:
  - 0.10
git:
  depth: 1
branches:
  only:
    - master
before_script:
  - "PACKAGE=sqlite-shell-linux-x86-3080002; wget http://www.sqlite.org/2013/$PACKAGE.zip && sudo unzip -o $PACKAGE -d /usr/local/bin && rm $PACKAGE.zip"
  - "sudo chmod +x /usr/local/bin/sqlite3"
  - "which sqlite3"
  - "sudo apt-get remove sqlite3"
  - "sudo apt-get install sqlite3"
  - "which sqlite3"
  - "sqlite3 --version"
