language: node_js
node_js:
  - 0.10
git:
  depth: 1
branches:
  only:
    - master
before_script:
  - "PACKAGE=sqlite-shell-linux-x86-3080002; wget http://www.sqlite.org/2013/$PACKAGE.zip && sudo unzip -o $PACKAGE -d ./ && rm $PACKAGE.zip"
  - "./sqlite3 --version"
  - "npm install wru"
